================================================================================
BILL PROCESSING PIPELINE - OPTIMIZED VERSION
================================================================================
Report Date: 2025-11-26 (SAS: 24071, File: 251126)
Previous Date: 2025-11-25 (SAS: 24070, File: 251125)

================================================================================
STEP 1: LOAD_EXDWH_LN_BILL - SCD TYPE 2 PROCESSING (OPTIMIZED)
================================================================================
Report Date: 2025-11-26 (SAS: 24071, File: 251126)
Previous Date: 2025-11-25 (SAS: 24070, File: 251125)
Processing in chunks of 5,000,000 records
--------------------------------------------------------------------------------
Looking for historical data:
  LOAN_BILL: /sas/python/virt_edw/Data_Warehouse/MIS/Job/LOAN/input/year=2025/month=11/day=25/LOAN_BILL.parquet - EXISTS
  ILOAN_BILL: /sas/python/virt_edw/Data_Warehouse/MIS/Job/LOAN/input/year=2025/month=11/day=25/ILOAN_BILL.parquet - EXISTS

1.1: Reading ENRH_LN_BILL in chunks...
  Total records: 97,027,080
  Processing chunk 1...
  Processing chunk 2...
  Processing chunk 3...
  Processing chunk 4...
  Processing chunk 5...
  Processing chunk 6...
  Processing chunk 7...
  Processing chunk 8...
  Processing chunk 9...
  Processing chunk 10...
  Processing chunk 11...
  Processing chunk 12...
  Processing chunk 13...
  Processing chunk 14...
  Processing chunk 15...
  Processing chunk 16...
  Processing chunk 17...
  Processing chunk 18...
  Processing chunk 19...
  Processing chunk 20...

1.2: Processing chunks with OPTIMIZED SCD logic...
  Loading only ACTIVE records from previous day (VALID_TO_DT = 2025-11-25)...
  ✓ Loaded 97,003,729 ACTIVE historical records (vs full dataset)
  SCD processing chunk 1/20...
Traceback (most recent call last):
  File "/sas/python/virt_edw/Data_Warehouse/MIS/Job/LOAN/MIS_LOAD_LN_BILL_UAT.py", line 596, in <module>
    loan_bill_path, iloan_bill_path = process_large_loan_bill_scd(
  File "/sas/python/virt_edw/Data_Warehouse/MIS/Job/LOAN/MIS_LOAD_LN_BILL_UAT.py", line 213, in process_large_loan_bill_scd
    chunk_result = process_scd_chunk_optimized(
  File "/sas/python/virt_edw/Data_Warehouse/MIS/Job/LOAN/MIS_LOAD_LN_BILL_UAT.py", line 293, in process_scd_chunk_optimized
    con.execute(f"""
duckdb.duckdb.BinderException: Binder Error: Cannot compare values of type DATE and type INTEGER_LITERAL - an explicit cast is required

LINE 14: ...                WHEN BILL_PAID_DT IS NOT NULL AND BILL_PAID_DT > 0 THEN 
                                                                           ^
