DATA REPTDATE;
   REPTDATE = &SAS_DT_SAS;
    STARTDATE = INTNX('MONTH',REPTDATE,0,'BEGIN');
    
    CALL SYMPUT('RDATE', REPTDATE);
    CALL SYMPUT('STRDATE', STARTDATE);
RUN;


DATA W5KTCTSDX;
   SET &_input;
   NEW = 'Y';
RUN;

DATA LOAN_BILL LOAN_BILL_KEEP;
   SET LN_BILL.LOAN_BILL ILN_BILL.ILOAN_BILL;
   IF VALID_TO_DT = &RDATE - 1 THEN DO;
      EXT = 'Y';
	  OUTPUT LOAN_BILL;
   END;
   ELSE OUTPUT LOAN_BILL_KEEP;
RUN;

PROC SQL;
CREATE TABLE MATCH AS 
SELECT T1.ACCTNO,
		 T1.NOTENO,
		 T1.BILL_DT,
		 T1.BILL_PAID_DT,
		 T1.BILL_AMT,
		 T1.BILL_AMT_PRIN,
		 T1.BILL_AMT_INT,
		 T1.BILL_AMT_ESCROW,
		 T1.BILL_AMT_FEE,
		 T1.BILL_NOT_PAY_AMT,
		 T1.BILL_NOT_PAY_AMT_PRIN,
		 T1.BILL_NOT_PAY_AMT_INT,
		 T1.BILL_NOT_PAY_AMT_ESCROW,
		 T1.BILL_NOT_PAY_AMT_FEE,
		 T1.COSTCTR,
 		 T1.PRODUCT,
  		 T1.VALID_FROM_DT,
       (&RDATE) AS VALID_TO_DT FORMAT DDMMYY10.
FROM LOAN_BILL T1 INNER JOIN W5KTCTSDX T2 ON (T1.ACCTNO=T2.ACCTNO) AND (T1.NOTENO=T2.NOTENO) AND (T1.BILL_DT=T2.BILL_DT) AND (T1.BILL_PAID_DT=T2.BILL_PAID_DT)
     AND (T1.BILL_AMT=T2.BILL_AMT) AND (T1.BILL_AMT_PRIN=T2.BILL_AMT_PRIN) AND (T1.BILL_AMT_INT=T2.BILL_AMT_INT) AND (T1.BILL_AMT_ESCROW=T2.BILL_AMT_ESCROW) 
     AND (T1.BILL_AMT_FEE=T2.BILL_AMT_FEE) AND (T1.BILL_NOT_PAY_AMT=T2.BILL_NOT_PAY_AMT) AND (T1.BILL_NOT_PAY_AMT_PRIN=T2.BILL_NOT_PAY_AMT_PRIN) 
     AND (T1.BILL_NOT_PAY_AMT_INT=T2.BILL_NOT_PAY_AMT_INT) AND (T1.BILL_NOT_PAY_AMT_ESCROW=T2.BILL_NOT_PAY_AMT_ESCROW) AND (T1.BILL_NOT_PAY_AMT_FEE=T2.BILL_NOT_PAY_AMT_FEE)
     AND (T1.COSTCTR=T2.COSTCTR) AND (T1.PRODUCT=T2.PRODUCT);
QUIT;

PROC SQL;
CREATE TABLE CHGREC AS 
SELECT T1.ACCTNO,
		 T1.NOTENO,
		 T1.BILL_DT,
		 T1.BILL_PAID_DT,
		 T1.BILL_AMT,
		 T1.BILL_AMT_PRIN,
		 T1.BILL_AMT_INT,
		 T1.BILL_AMT_ESCROW,
		 T1.BILL_AMT_FEE,
		 T1.BILL_NOT_PAY_AMT,
		 T1.BILL_NOT_PAY_AMT_PRIN,
		 T1.BILL_NOT_PAY_AMT_INT,
		 T1.BILL_NOT_PAY_AMT_ESCROW,
		 T1.BILL_NOT_PAY_AMT_FEE,
		 T1.COSTCTR,
 		 T1.PRODUCT,
  		 T1.VALID_FROM_DT,
       T1.VALID_TO_DT,
       T2.NEW
FROM LOAN_BILL T1 LEFT JOIN W5KTCTSDX T2 ON (T1.ACCTNO=T2.ACCTNO) AND (T1.NOTENO=T2.NOTENO) AND (T1.BILL_DT=T2.BILL_DT) AND (T1.BILL_PAID_DT=T2.BILL_PAID_DT)
     AND (T1.BILL_AMT=T2.BILL_AMT) AND (T1.BILL_AMT_PRIN=T2.BILL_AMT_PRIN) AND (T1.BILL_AMT_INT=T2.BILL_AMT_INT) AND (T1.BILL_AMT_ESCROW=T2.BILL_AMT_ESCROW) 
     AND (T1.BILL_AMT_FEE=T2.BILL_AMT_FEE) AND (T1.BILL_NOT_PAY_AMT=T2.BILL_NOT_PAY_AMT) AND (T1.BILL_NOT_PAY_AMT_PRIN=T2.BILL_NOT_PAY_AMT_PRIN) 
     AND (T1.BILL_NOT_PAY_AMT_INT=T2.BILL_NOT_PAY_AMT_INT) AND (T1.BILL_NOT_PAY_AMT_ESCROW=T2.BILL_NOT_PAY_AMT_ESCROW) AND (T1.BILL_NOT_PAY_AMT_FEE=T2.BILL_NOT_PAY_AMT_FEE)
     AND (T1.COSTCTR=T2.COSTCTR) AND (T1.PRODUCT=T2.PRODUCT)
WHERE T2.NEW IS NULL;
QUIT;


PROC SQL;
CREATE TABLE UPDATEX AS 
SELECT T2.ACCTNO,
		 T2.NOTENO,
		 T2.BILL_DT,
		 T2.BILL_PAID_DT,
		 T2.BILL_AMT,
		 T2.BILL_AMT_PRIN,
		 T2.BILL_AMT_INT,
		 T2.BILL_AMT_ESCROW,
		 T2.BILL_AMT_FEE,
		 T2.BILL_NOT_PAY_AMT,
		 T2.BILL_NOT_PAY_AMT_PRIN,
		 T2.BILL_NOT_PAY_AMT_INT,
		 T2.BILL_NOT_PAY_AMT_ESCROW,
		 T2.BILL_NOT_PAY_AMT_FEE,
		 T2.COSTCTR,
 		 T2.PRODUCT,
  		 (&RDATE) AS VALID_FROM_DT FORMAT DDMMYY10.,
       (&RDATE) AS VALID_TO_DT FORMAT DDMMYY10.,
       T1.EXT
FROM LOAN_BILL T1 RIGHT JOIN W5KTCTSDX T2 ON (T1.ACCTNO=T2.ACCTNO) AND (T1.NOTENO=T2.NOTENO) AND (T1.BILL_DT=T2.BILL_DT) AND (T1.BILL_PAID_DT=T2.BILL_PAID_DT)
     AND (T1.BILL_AMT=T2.BILL_AMT) AND (T1.BILL_AMT_PRIN=T2.BILL_AMT_PRIN) AND (T1.BILL_AMT_INT=T2.BILL_AMT_INT) AND (T1.BILL_AMT_ESCROW=T2.BILL_AMT_ESCROW) 
     AND (T1.BILL_AMT_FEE=T2.BILL_AMT_FEE) AND (T1.BILL_NOT_PAY_AMT=T2.BILL_NOT_PAY_AMT) AND (T1.BILL_NOT_PAY_AMT_PRIN=T2.BILL_NOT_PAY_AMT_PRIN) 
     AND (T1.BILL_NOT_PAY_AMT_INT=T2.BILL_NOT_PAY_AMT_INT) AND (T1.BILL_NOT_PAY_AMT_ESCROW=T2.BILL_NOT_PAY_AMT_ESCROW) AND (T1.BILL_NOT_PAY_AMT_FEE=T2.BILL_NOT_PAY_AMT_FEE)
     AND (T1.COSTCTR=T2.COSTCTR) AND (T1.PRODUCT=T2.PRODUCT)
WHERE T1.EXT IS NULL;
QUIT;


PROC SQL;
   CREATE TABLE LOAN_BILL AS 
   SELECT * FROM MATCH OUTER UNION CORR 
   SELECT * FROM UPDATEX OUTER UNION CORR 
   SELECT * FROM CHGREC
   ;
QUIT;

DATA LOAN_BILL;
   SET LOAN_BILL LOAN_BILL_KEEP;
RUN;

PROC SORT DATA=LOAN_BILL(DROP=NEW EXT) OUT=W5KTGIYY;BY ACCTNO NOTENO BILL_DT VALID_FROM_DT VALID_TO_DT;RUN; 
