PROC   REPORT DATA=NPGS5 NOWD HEADSKIP HEADLINE SPLIT='*';
COLUMN CVAR02 CVAR03 CVAR04 CVARX1 CVAR06 CVARX5 CVAR16 CVAR08
       CVAR09 CVAR17 ACCRUALX CVAR10 CVAR11 CVAR12A CVAR13
       CVARX2 CVARX3 CVAR01;
DEFINE CVAR02   / DISPLAY FORMAT=$3.       'SCH';
DEFINE CVAR03   / DISPLAY FORMAT=$15.      'IC /BUSS. NUM.';
DEFINE CVAR04   / DISPLAY FORMAT=$100.     'NAME OF CUSTOMER';
DEFINE CVARX1   / DISPLAY FORMAT=$10.      '              ';
DEFINE CVAR06   / DISPLAY FORMAT=10.       'ACCOUNT NUMBER';
DEFINE CVARX5   / DISPLAY FORMAT=$10.      'DISBURSE*DATE';
DEFINE CVAR16   / DISPLAY FORMAT=$8.       'FACILITY*TYPE';
DEFINE CVAR08   / DISPLAY FORMAT=10.2      'LOAN AMOUNT';
DEFINE CVAR09   / DISPLAY FORMAT=10.2      'O/S BALANCE';
DEFINE CVAR17   / DISPLAY FORMAT=10.2      'PRINCIPAL*BALANCE';
DEFINE ACCRUALX / DISPLAY FORMAT=10.2      'INTEREST*BALANCE';
DEFINE CVAR10   / DISPLAY FORMAT=10.2      'CREDIT*BALANCE';
DEFINE CVAR11   / DISPLAY FORMAT=7.        'ARREARS';
DEFINE CVAR12A  / DISPLAY FORMAT=$3.       'ST ';
DEFINE CVAR13   / DISPLAY FORMAT=$10.      'NPL DATE';
DEFINE CVARX2   / DISPLAY FORMAT=$10.      'NPL*NOTIFICATN*DATE';
DEFINE CVARX3   / DISPLAY FORMAT=$6.       'NPL*REASON';
DEFINE CVAR01   / DISPLAY FORMAT=10.       'APPLICATN*NUMBER';
*;
