DATA REPTDATE;
  SET DEPOSIT.REPTDATE;
  SELECT;
     WHEN( 1<= DAY(REPTDATE)<=  8) CALL SYMPUT('NOWK', PUT('1', $1.));
     WHEN( 9<= DAY(REPTDATE)<= 15) CALL SYMPUT('NOWK', PUT('2', $1.));
     WHEN(16<= DAY(REPTDATE)<= 22) CALL SYMPUT('NOWK', PUT('3', $1.));
     OTHERWISE                     CALL SYMPUT('NOWK', PUT('4', $1.));
  END;
  CALL SYMPUT('REPTYEAR',PUT(REPTDATE,YEAR2.));
  CALL SYMPUT('REPTMON',PUT(MONTH(REPTDATE),Z2.));
  CALL SYMPUT('REPTDAY',PUT(DAY(REPTDATE),Z2.));
  CALL SYMPUT('REPTDT',PUT(REPTDATE,8.));
RUN;

DATA EGOLD;
   INFILE EGOLD;
   INPUT  @002 TRXNYY       4.
          @006 TRXNMM       2.
          @008 TRXNDD       2.
          @013 ACCTNO      10.
          @026 MPURCGM     10.
          @042 MSALEGM     10.
          @058 BRANCH       3.
          @064 MPURCPR     11.6   /* SELLING PRICE */
          @078 MPURCAMT    14.2
          @095 MSALEPR     11.6   /* BUYING PRICE */
          @109 MSALEAMT    14.2;
   TRXNDATE = MDY(TRXNMM,TRXNDD,TRXNYY);
   REPTDATE = &REPTDT;
RUN;

DATA EGOLD;
     SET EGOLD;
     FORMAT CHANNELIND     $8.;
     CHANNELIND = 'EBANKING';
RUN;

DATA OTHER;
   INFILE OTHER;
   INPUT  @002 TRXNYY       4.
          @006 TRXNMM       2.
          @008 TRXNDD       2.
          @013 ACCTNO      10.
          @026 MPURCGM     10.
          @042 MSALEGM     10.
          @058 BRANCH      3.
          @064 MPURCPR     11.6   /* SELLING PRICE */
          @078 MPURCAMT    14.2
          @095 MSALEPR     11.6   /* BUYING PRICE */
          @109 MSALEAMT    14.2
          @125 TRANCODE     3.
          @128 CHANNEL     3.;
   TRXNDATE = MDY(TRXNMM,TRXNDD,TRXNYY);
   REPTDATE = &REPTDT;
RUN;

DATA OTHER;
     SET OTHER;
     FORMAT CHANNELIND     $8.;
     CHANNELIND = 'OTHER';
RUN;

DATA GOLDTRAN;
     SET EGOLD OTHER;
RUN;

%MACRO APPEND;
%IF "&REPTDAY" EQ "01" OR
    "&REPTDAY" EQ "09" OR
    "&REPTDAY" EQ "16" OR
    "&REPTDAY" EQ "23" %THEN
    %DO;
       DATA MIS.GOLDTRAN&REPTMON&NOWK;
          SET GOLDTRAN;
       RUN;
    %END;
%ELSE %DO;
       DATA MIS.GOLDTRAN&REPTMON&NOWK;
          SET MIS.GOLDTRAN&REPTMON&NOWK;
          IF REPTDATE EQ &REPTDT THEN DELETE;
       RUN;
       PROC APPEND DATA=GOLDTRAN
                   BASE=MIS.GOLDTRAN&REPTMON&NOWK;
       RUN;
%END;
%MEND APPEND;
%APPEND;

DATA TEMP.GOLDTRAN&REPTMON&NOWK&REPTYEAR;
   SET MIS.GOLDTRAN&REPTMON&NOWK;
RUN;
