EIBMCHNL

DATA REPTDATE;
   REPTDATE=TODAY()-1;
   CALL SYMPUT('REPTYEAR', PUT(REPTDATE, YEAR2.));
   CALL SYMPUT('REPTMON', PUT(MONTH(REPTDATE), Z2.));
   CALL SYMPUT('REPTDAY', PUT(DAY(REPTDATE), Z2.));
   CALL SYMPUT('RDATE', PUT(REPTDATE, DDMMYY8.));
RUN;

DATA CHANNEL(DROP=REPTDATE);
   INFILE CHANNEL FIRSTOBS=1;
   INPUT @001  CHANNEL    $UPCASE5.      /* CHANNEL                */
         @006  TOLPROMPT         8.      /* TOTAL PROMPTED         */
         @014  TOLUPDATE         8.      /* TOTAL UPDATED          */
         ;
         REPTDATE=TODAY()-2;
         MONTH=PUT(REPTDATE,MONYY5.);
RUN;
PROC PRINT DATA=CHANNEL;RUN;

PROC APPEND DATA=CHANNEL BASE=CRMWH.CHANNEL_SUM FORCE;RUN;
PROC PRINT DATA=CRMWH.CHANNEL_SUM;RUN;

DATA BRANCH;
   INFILE BRANCH FIRSTOBS=1;
   INPUT @001  BRANCHNO          5.      /* BRANCH NUMBER          */
         @006  TOLPROMPT         8.      /* TOTAL PROMPTED         */
         @014  TOLUPDATE         8.      /* TOTAL UPDATED          */
         ;
RUN;

DATA BCODE;
   INFILE BCODE;
   INPUT @002   BRANCHNO       3.        /* BRANCH NUMBER          */
         ;
RUN;

PROC SORT DATA=BCODE;BY BRANCHNO;RUN;
PROC SORT DATA=BRANCH;BY BRANCHNO;RUN;

DATA CRMWH.OTC_DETAIL_&REPTMON&REPTYEAR;
   MERGE BCODE(IN=A) BRANCH(IN=B);BY BRANCHNO;
   IF TOLPROMPT=. THEN DO TOLPROMPT=0;END;
   IF TOLUPDATE=. THEN DO TOLUPDATE=0;END;
   IF A;
RUN;




EIBMCHN2

DATA REPTDATE;
   REPTDATE=TODAY()-1;
   CALL SYMPUT('REPTYEAR', PUT(REPTDATE, YEAR2.));
   CALL SYMPUT('REPTMON', PUT(MONTH(REPTDATE), Z2.));
   CALL SYMPUT('REPTDAY', PUT(DAY(REPTDATE), Z2.));
   CALL SYMPUT('RDATE', PUT(REPTDATE, DDMMYY8.));
RUN;

     DATA SUM;
        INFILE CHANNEL;
        INPUT    @022 ATM      10.
                 @037 EBK      10.
                 @052 OTC      10.
                 @067 TOTAL    10.
                 @080 DATE    $10.
                 ;
     RUN;
     DATA UAT(KEEP=DESC ATM EBK OTC TOTAL DATE);
      SET SUM;
      IF _N_ = 1 THEN DESC='TOTAL PROMPT BASE';
      IF _N_ = 2 THEN DESC='TOTAL UPDATED';
     RUN;
     PROC PRINT DATA=UAT; RUN;
     *;
    PROC SQL;
    CREATE TABLE UAT AS SELECT
    DESC,ATM,EBK,OTC,TOTAL,DATE
    FROM UAT;
    QUIT;
     *;
     PROC APPEND DATA=UAT BASE=CHN.CHANNEL_UPDATE FORCE; RUN;
     *;


 Please help to create the last month base parquet as below.

libname crm '/dwh/crm';

 PROC APPEND DATA=CHANNEL BASE=CRMWH.CHANNEL_SUM FORCE;RUN; 
 PROC PRINT DATA=CRMWH.CHANNEL_SUM;RUN;                     

PROC APPEND DATA=UAT BASE=CHN.CHANNEL_UPDATE FORCE; RUN; 

REPTDATE = datetime.today() - timedelta(days=1)
PREVDATE = REPTDATE - timedelta(days=1)
SAS_ORIGIN = datetime(1960, 1, 1)
RDATE = (REPTDATE - SAS_ORIGIN).days



Paths:

BASE_INPUT_PATH = Path("/host/cis/parquet/")
BASE_PATH = "/host/mis/parquet/crm"
BCODE_LOOKUP = "/sasdata/rawdata/lookup/LKP_BRANCH"

CIS_DATA_PATH = BASE_INPUT_PATH / f"year={CIS_YEAR}/month={CIS_MONTH}/day={CIS_DAY}"
TODAY_CHANNEL_SUM = CIS_DATA_PATH / "CIPHONET_ALL_SUMMARY.parquet"
TODAY_CHANNEL_UPDATE = CIS_DATA_PATH / "CIPHONET_FULL_SUMMARY.parquet"
OTC_SUMMARY_SRC = CIS_DATA_PATH / "CIPHONET_OTC_SUMMARY.parquet"

LAST_MONTH_PATH = f"{BASE_PATH}/year={LAST_MONTH_YEAR}/month={LAST_MONTH_NUM:02d}"
CURRENT_MONTH_PATH = f"{BASE_PATH}/year={CURRENT_MONTH_YEAR}/month={CURRENT_MONTH_NUM:02d}"
CRMWH_DIR = Path(BASE_PATH) / "CRMWH"

for path in [LAST_MONTH_PATH, CURRENT_MONTH_PATH, str(CRMWH_DIR)]:
    os.makedirs(path, exist_ok=True)

LAST_CHANNEL_SUM = f"{LAST_MONTH_PATH}/CHANNEL_SUM.parquet"
LAST_CHANNEL_UPDATE = f"{LAST_MONTH_PATH}/CHANNEL_UPDATE.parquet"
CURRENT_CHANNEL_SUM = f"{CURRENT_MONTH_PATH}/CHANNEL_SUM.parquet"
CURRENT_CHANNEL_UPDATE = f"{CURRENT_MONTH_PATH}/CHANNEL_UPDATE.parquet"
