DATA REPTDATE;
   REPTDATE=TODAY()-1;
   CALL SYMPUT('REPTYEAR', PUT(REPTDATE, YEAR2.));
   CALL SYMPUT('REPTMON', PUT(MONTH(REPTDATE), Z2.));
   CALL SYMPUT('REPTDAY', PUT(DAY(REPTDATE), Z2.));
   CALL SYMPUT('RDATE', PUT(REPTDATE, DDMMYY8.));
RUN;

DATA CHANNEL(DROP=REPTDATE);
   INFILE CHANNEL FIRSTOBS=1;
   INPUT @001  CHANNEL    $UPCASE5.      /* CHANNEL                */
         @006  TOLPROMPT         8.      /* TOTAL PROMPTED         */
         @014  TOLUPDATE         8.      /* TOTAL UPDATED          */
         ;
         REPTDATE=TODAY()-2;
         MONTH=PUT(REPTDATE,MONYY5.);
RUN;
PROC PRINT DATA=CHANNEL;RUN;

PROC APPEND DATA=CHANNEL BASE=CRMWH.CHANNEL_SUM FORCE;RUN;
PROC PRINT DATA=CRMWH.CHANNEL_SUM;RUN;

DATA BRANCH;
   INFILE BRANCH FIRSTOBS=1;
   INPUT @001  BRANCHNO          5.      /* BRANCH NUMBER          */
         @006  TOLPROMPT         8.      /* TOTAL PROMPTED         */
         @014  TOLUPDATE         8.      /* TOTAL UPDATED          */
         ;
RUN;

DATA BCODE;
   INFILE BCODE;
   INPUT @002   BRANCHNO       3.        /* BRANCH NUMBER          */
         ;
RUN;

PROC SORT DATA=BCODE;BY BRANCHNO;RUN;
PROC SORT DATA=BRANCH;BY BRANCHNO;RUN;

DATA CRMWH.OTC_DETAIL_&REPTMON&REPTYEAR;
   MERGE BCODE(IN=A) BRANCH(IN=B);BY BRANCHNO;
   IF TOLPROMPT=. THEN DO TOLPROMPT=0;END;
   IF TOLUPDATE=. THEN DO TOLUPDATE=0;END;
   IF A;
RUN;















DATA REPTDATE;
   REPTDATE=TODAY()-1;
   CALL SYMPUT('REPTYEAR', PUT(REPTDATE, YEAR2.));
   CALL SYMPUT('REPTMON', PUT(MONTH(REPTDATE), Z2.));
   CALL SYMPUT('REPTDAY', PUT(DAY(REPTDATE), Z2.));
   CALL SYMPUT('RDATE', PUT(REPTDATE, DDMMYY8.));
RUN;

     DATA SUM;
        INFILE CHANNEL;
        INPUT    @022 ATM      10.
                 @037 EBK      10.
                 @052 OTC      10.
                 @067 TOTAL    10.
                 @080 DATE    $10.
                 ;
     RUN;
     DATA UAT(KEEP=DESC ATM EBK OTC TOTAL DATE);
      SET SUM;
      IF _N_ = 1 THEN DESC='TOTAL PROMPT BASE';
      IF _N_ = 2 THEN DESC='TOTAL UPDATED';
     RUN;
     PROC PRINT DATA=UAT; RUN;
     *;
    PROC SQL;
    CREATE TABLE UAT AS SELECT
    DESC,ATM,EBK,OTC,TOTAL,DATE
    FROM UAT;
    QUIT;
     *;
     PROC APPEND DATA=UAT BASE=CHN.CHANNEL_UPDATE FORCE; RUN;
     *;
