Report Date: 2026-06-14
Previous Month: 05
Next Month Start: 20260701
Loaded BTBASE file: /sas/python/virt_edw/Data_Warehouse/MIS/XMIS/input/prod/btbase05.sas7bdat
BTBASE metadata: ['TRANSREX', 'BRANCH', 'ACCTNO', 'OUTSTAND', 'TRANSREF', 'FACILITY', 'PRODTYPE', 'DAYS']
BTBASE rows: 137
Loaded BTDTL file: /sas/python/virt_edw/Data_Warehouse/MIS/XMIS/input/prod/btdtl260614.sas7bdat
BTDTL metadata: ['TRANSREX', 'CREATTYP', 'BRANCH', 'APPLCODE', 'ACCTNO', 'SUBACCT', 'CREATYYMMDD', 'EXPIRDS', 'SYNDICAT', 'SPECIALF', 'PURPOSES', 'AANUMBER', 'INTRATE', 'SPREAD', 'INFUNDRT', 'DISCNTB', 'DISCNTF', 'TRANXMT', 'EXCHRTE', 'FORCURR', 'LIABCODE', 'BTREL1', 'RELFROM', 'CURRENCY', 'APPRLIMT', 'APPRLIM2', 'OFFAPIND', 'TFDESC01', 'TFCNTR01', 'TFCNTR03', 'TFCNTR04', 'TFINDR01', 'TFINDR02', 'TFINDR03', 'TFINDR04', 'TFINDR05', 'ISSDTEYYMMDD', 'SINDICAT', 'SUBPROD', 'FACLINE', 'PRODGRP', 'DIRCTIND', 'TRANSREL', 'COMMRATE', 'DISCRATE', 'CONRATE_IND', 'INTBASE', 'PLUSMINUS', 'NUMDAYS', 'BACOM', 'DISCOUNT_PROCEED', 'MTD_TAWIDH_AMT', 'MTD_GHARAMAH_AMT', 'REPAY_SOURCE', 'REPAY_TYPE_CD', 'PROP_DEVELOP_FIN_IND', 'CLIMATE_PRIN_TAXONOMY_CLASS', 'CLIMATE_MITIGATE_GP1_FLG', 'CLIMATE_ADAPT_GP2_FLG', 'CLIMATE_ENVIRONMT_GP3_FLG', 'CLIMATE_TRANSITION_GP4_FLG', 'CLIMATE_PROHIBIT_GP5_FLG', 'SOURCE_INCOME_CURRENCY_CD', 'AADATE', 'REFERRAL_BRANCH', 'APPL_COMMERCIAL_TAG', 'COMBRATE', 'AA_APPROVED_DT', 'BTREL2', 'BTREL3', 'BTREL4', 'NOLEVEL', 'OUTSTAND', 'CERTNO', 'COLLECNO', 'PAYBKNO', 'ADDRLN3', 'ADDRLN4', 'CNTRY', 'PREBKNO', 'PRINAMT_MYRX', 'INTAMT_MYRX', 'OTH_CHARGEX', 'TRANSREF', 'MATUREDS', 'RETAILID', 'STATE', 'SCORE1', 'SCORE2', 'BUSREGN', 'SECTOR', 'SM_STATUS', 'IA_LRU', 'SM_DATE', 'ASCORE_LTST', 'ASCORE_PERM', 'APVDATE', 'INDUSTRIAL_SECTOR_CD', 'LEGAL_ACTION_CD', 'LEGAL_ACTION_DT', 'CCPT_LTST_REVIEW_DT', 'FDB_TAG', 'FDB_TAG_DT', 'FDB_SCORING_DT', 'CUSTCODE', 'DNBFISME', 'ACCTNON', 'ACCTNOX', 'PRINAMT', 'INTAMT', 'INTYTD', 'FIXFLT', 'CALBASP', 'INTAMT_MYR', 'PRINAMT_MYR', 'TENOR_INT', 'OTH_CHARGE', 'IRIA', 'REPTDAT1', 'RDAY1', 'ISSYY', 'ISSMM', 'ISSDTX', 'FACILITY', 'PREFIX', 'CREATDS', 'ISSDTE', 'MATDATE', 'EXPRDATE', 'DIA_PAST01_MTH', 'DIA_PAST02_MTH', 'DIA_PAST03_MTH', 'DIA_PAST04_MTH', 'DIA_PAST05_MTH', 'DIA_PAST06_MTH', 'DIA_PAST07_MTH', 'DIA_PAST08_MTH', 'DIA_PAST09_MTH', 'DIA_PAST10_MTH', 'DIA_PAST11_MTH', 'DIA_PAST12_MTH', 'FORATE']
BTDTL rows: 43012
BASE transformation complete. Rows: 137
Traceback (most recent call last):
  File "/sas/python/virt_edw/Data_Warehouse/MIS/XMIS/EIBD2CBT.py", line 95, in <module>
    btdtl_trans = con.execute("""
_duckdb.BinderException: Binder Error: Referenced column "PRODTYPE" not found in FROM clause!
Candidate bindings: "PRODGRP", "EXPRDATE", "APVDATE", "SUBPROD", "PURPOSES"

LINE 14:                ELSE CAST(PRODTYPE AS INT)
